const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const { Process } = require('../Brains')

let collections = {
	Access: {attributes_right:  String, attributes_transferable: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},

	AgeRange: {attributes_minimum:  String, attributes_maximum: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},

	Availability: {attributes_quantity:  String,  attributes_per_household: String,attributes_back_order: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},

	Booking: {
		attributes_date_start:  String, attributes_date_end:  String, attributes_time_start: String ,attributes_time_end:  String, attributes_minimum:  String, attributes_maximum: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }
	},
	Credential: {attributes_expiration:  String, attributes_start:  String, attributes_end: String ,attributes_staff: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},

	DateRange: {attributes_date_start:  String, attributes_date_end: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},
	Description: {attributes_header:  String, attributes_content: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},
	Discount: {attributes_amount:  String, attributes_code:  String, attributes_max_usage: String ,attributes_user_usage:  String, attributes_kickback: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},
	FileManagement: {attributes_link:  String, attributes_type:  String, attributes_required: String ,attributes_expiration: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},
	Gallery: {attributes_link:  String, attributes_content: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},
	Grouping: {attributes_access:  String, attributes_agerange:  String, attributes_availability:  String, attributes_booking:  String, attributes_credential:  String, attributes_daterange:  String, attributes_description:  String, attributes_discount:  String, attributes_filemanagement:  String, attributes_gallery:  String, attributes_lifespan:  String, attributes_grouping:  String, attributes_pricing:  String, attributes_product:  String, attributes_productname:  String, attributes_quantityrange:  String, attributes_question:  String, attributes_sizerange:  String, attributes_timerange:  String, attributes_variation:  String, attributes_warranty:  String, attributes_wholesale: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},
	Lifespan: {attributes_amount:  String, attributes_deviation:  String, attributes_expansion: String ,attributes_diminish: String , attributes_title: String, attributes_price: String, attributes_type: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},
	Pricing: {attributes_amount:  String, attributes_minimum:  String, attributes_maximum: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},
	ProductName: {attributes_prefix:  String, attributes_suffix: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},
	QuantityRange: {attributes_content: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},
	Question: {attributes_question:  String, attributes_example:  String, attributes_required: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},
	Product: {attributes_description:  String, attributes_icon:  String, attributes_image:  String, attributes_video: String ,attributes_parent: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},
	SizeRange: {attributes_amount:  String, attributes_field:  String, attributes_price: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},
	TimeRange: {attributes_start_time:  String, attributes_end_time: String , attributes_days: [{type: String}], attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},
	Variation: {attributes_price:  String, attributes_max_product_qty:  String, attributes_option:  String, attributes_included: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},
	Warranty: {attributes_packaging:  String, attributes_usage:  String, attributes_content: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},
	Wholesale: {attributes_minimum:  String, attributes_amount:  String, attributes_maximum: String , attributes_title: String, attributes_price: String, attributes_section: [{ type: Schema.Types.ObjectId, ref: 'sections'}], attributes_published: { type: String},  attributes_public: { type: String,  default: 'false' }},
}


module.exports = {
	...collections
};